# -*- coding: utf-8 -*-
from .common_views import *
from .partner_views import *
from .product_views import *
from .component_views import *
from .dashboard_views import *
from .case_views import *
from .review_request_views import *
from .request_csv_views import *
from .csv2db_views import *
from .backlog_views import *  
from .language_views import *
from .individual_views import *
from .individual_detail_views import *
from .partner_report_views import *
from .partner_nonpartner_report_views import *
from .review_request_report_view import *
from .period_set_views import *
from .component_report_views import *
from .da_report_views import *
from .user_views import *
from .home_views import *
from .yearly_report import *